# The URL the site will be built for
base_url = "https://csuwangj.github.io/ZDaily/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
title = "CSUwangj's daily challenge"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "DogFood"
generate_feed = true
feed_filename = "atom.xml"
taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
  {name = "archives", rss = true},
]

[extra]
site_name = "ZDaily"
menu_items = [
  {url = "$BASE_URL", name = "Home", icon = "fa fa-home"},
  {url = "$BASE_URL/about", name = "About", icon = "fa fa-user-circle-o"},
  {url = "$BASE_URL/categories", name = "Categories", icon = "fa fa-book"},
  {url = "$BASE_URL/tags", name = "Tags", icon = "fa fa-tags"},
  {url = "$BASE_URL/archives", name = "Archives", icon = "fa fa-inbox"},
]
author = "CSUwangj"
quote = "Just keep in mind that hacking is very rarely in a sequence."
links = [
  {name = "blog", url = "https://CSUwangj.github.io/"}
]
author_links = [
  {name = "Github", url = "https://github.com/CSUwangj", favion = "fa fw fa-github"},
  {name = "EMail", url = "mailto:CSUwangj@protonmail.com", favion = "fa fw fa-envelope"},
]
copyright_year = "2018-2020"
avatar = "img/avatar.png"
katex_enabled = true